import type { Item, Subject } from "@/lib/types";

export const SUBJECTS: Subject[] = [
  { code: "INF1005", name: "Fundamentos de Programação", dept: "Informática" },
  { code: "INF1010", name: "Estrutura de Dados", dept: "Informática" },
  { code: "INF1023", name: "Laboratório de Programação", dept: "Informática" },
  { code: "INF1034", name: "Introdução à Computação", dept: "Informática" },
  { code: "INF1316", name: "Sistemas Operacionais", dept: "Informática" },
  { code: "INF1400", name: "Banco de Dados", dept: "Informática" },
  { code: "MAT1153", name: "Cálculo a Uma Variável", dept: "Matemática" },
  { code: "MAT1154", name: "Álgebra Linear", dept: "Matemática" },
  { code: "FIS1053", name: "Física 1", dept: "Física" },
  { code: "TEO1000", name: "Introdução ao Pensamento Cristão", dept: "Formação Humanística" },
  { code: "FIL1001", name: "Introdução à Filosofia", dept: "Formação Humanística" },
];

export const DEPT_ORDER = ["Informática", "Matemática", "Física", "Formação Humanística"];
export const DOC_TYPES = ["Resumo", "Prova Antiga", "Lista de Exercícios", "Slides", "Anotações"];
export const FORUM_TAGS = ["Dúvida", "Discussão", "Aviso", "Recurso"];

export const SEED_ITEMS: Item[] = [
  { id: "m1", kind: "material", subjectCode: "INF1034", subjectName: "Introdução à Computação", title: "Resumo: Círculo Trigonométrico para Turtle Graphics", docType: "Resumo", author: "Dedey", date: "2026-08-14", score: 18, downloads: 24, pages: 3, description: "Seno, cosseno e tangente aplicados ao posicionamento de linhas e espirais no Turtle — a base que usei pra Tarefa 15B (nuvem de palavras).", comments: [{ author: "Bia N.", body: "Isso ajudou demais a entender o ângulo da espiral, obrigada!", date: "2026-08-14" }] },
  { id: "m2", kind: "material", subjectCode: "INF1010", subjectName: "Estrutura de Dados", title: "Prova Antiga P1 2025.2 — Estrutura de Dados", docType: "Prova Antiga", author: "Lucas P.", date: "2026-08-11", score: 37, downloads: 91, pages: 6, description: "Prova completa com questões sobre listas encadeadas, pilhas e filas. Sem gabarito oficial, mas com as minhas respostas comentadas.", comments: [{ author: "Pedro L.", body: "A questão 4 caiu quase igual pra minha turma.", date: "2026-08-12" }] },
  { id: "m3", kind: "material", subjectCode: "INF1005", subjectName: "Fundamentos de Programação", title: "Lista 3 resolvida — Fundamentos de Programação", docType: "Lista de Exercícios", author: "Marina S.", date: "2026-08-05", score: 22, downloads: 58, pages: 2, description: "Todos os exercícios de repetição e vetores resolvidos e comentados em Python.", comments: [] },
  { id: "m4", kind: "material", subjectCode: "MAT1153", subjectName: "Cálculo a Uma Variável", title: "Resumo completo — Limites e Derivadas", docType: "Resumo", author: "Rafa A.", date: "2026-07-28", score: 63, downloads: 124, pages: 5, description: "Regras de derivação, limites notáveis e exemplos passo a passo, do jeito que já caiu nas provas dos últimos períodos.", comments: [{ author: "Carol M.", body: "O exemplo da regra da cadeia ficou perfeito, salvou minha revisão.", date: "2026-07-30" }] },
  { id: "m5", kind: "material", subjectCode: "MAT1154", subjectName: "Álgebra Linear", title: "Slides de revisão — Autovalores e Autovetores", docType: "Slides", author: "Bia N.", date: "2026-07-25", score: 19, downloads: 45, pages: 14, description: "Slides que fiz pra P2, com um exemplo numérico completo de diagonalização de matriz.", comments: [] },
  { id: "m6", kind: "material", subjectCode: "FIS1053", subjectName: "Física 1", title: "Anotações de aula — Cinemática", docType: "Anotações", author: "João V.", date: "2026-08-02", score: 11, downloads: 30, pages: 8, description: "Anotações das três primeiras semanas, com os desenhos dos gráficos de posição por tempo.", comments: [] },
  { id: "m7", kind: "material", subjectCode: "INF1400", subjectName: "Banco de Dados", title: "Resumo — Modelagem ER e Normalização", docType: "Resumo", author: "Dedey", date: "2026-08-09", score: 20, downloads: 33, pages: 4, description: "Passo a passo pra montar o diagrama entidade-relacionamento e normalizar até a 3FN, com exemplo de sistema de biblioteca.", comments: [] },
  { id: "m8", kind: "material", subjectCode: "INF1316", subjectName: "Sistemas Operacionais", title: "Prova Antiga 2025.1 — Sistemas Operacionais", docType: "Prova Antiga", author: "Marina S.", date: "2026-07-22", score: 16, downloads: 41, pages: 5, description: "Questões sobre escalonamento de processos e gerência de memória.", comments: [] },
  { id: "p1", kind: "post", subjectCode: "INF1034", subjectName: "Introdução à Computação", title: "Como preencher a nuvem de palavras sem sobrepor as palavras?", tag: "Dúvida", author: "Dedey", date: "2026-08-15", score: 9, body: "Estou fazendo a Tarefa 15B e as palavras maiores ficam sempre por cima das menores. Alguém achou uma lógica de posicionamento em espiral que funcionou bem com a turtle?", comments: [{ author: "Ana C.", body: "Eu fiz uma espiral aumentando o raio aos poucos e testando colisão com o retângulo de cada palavra antes de desenhar.", date: "2026-08-15" }, { author: "João V.", body: "Também travei nisso, vou tentar essa ideia da colisão.", date: "2026-08-16" }] },
  { id: "p2", kind: "post", subjectCode: "INF1034", subjectName: "Introdução à Computação", title: "Ninguém entendeu o controle de volume da Tarefa 11 com Pygame?", tag: "Dúvida", author: "Ana C.", date: "2026-08-13", score: 6, body: "O som toca certo, mas o volume não muda quando arrasto a barra. Estou usando set_volume, será que é a escala de 0 a 1?", comments: [{ author: "Dedey", body: "É isso mesmo — o set_volume espera de 0.0 a 1.0, tem que converter a posição do slider pra essa escala.", date: "2026-08-13" }] },
  { id: "p3", kind: "post", subjectCode: "INF1010", subjectName: "Estrutura de Dados", title: "Lista encadeada simples ou dupla: quando compensa usar cada uma?", tag: "Dúvida", author: "Pedro L.", date: "2026-08-10", score: 14, body: "Entendo a implementação, mas não sei quando compensa o custo extra de manter o ponteiro anterior. Alguém tem um exemplo real?", comments: [{ author: "Lucas P.", body: "Duplamente encadeada compensa quando você precisa andar pra trás com frequência, tipo em um player de música.", date: "2026-08-10" }, { author: "Marina S.", body: "Um bom exemplo também é o histórico de um navegador.", date: "2026-08-11" }, { author: "Pedro L.", body: "Fez sentido, valeu!", date: "2026-08-11" }] },
  { id: "p4", kind: "post", subjectCode: "MAT1153", subjectName: "Cálculo a Uma Variável", title: "Dica: tabela de derivadas que caiu 3 vezes na prova", tag: "Recurso", author: "Rafa A.", date: "2026-07-29", score: 27, body: "Fiz uma tabela com as derivadas que mais aparecem nas provas dos últimos períodos, deve ajudar quem tá revisando pra P2.", comments: [{ author: "Bia N.", body: "Isso é ouro, obrigada por compartilhar.", date: "2026-07-29" }] },
  { id: "p5", kind: "post", subjectCode: "INF1005", subjectName: "Fundamentos de Programação", title: "IndentationError mesmo com a identação certa, alguém mais?", tag: "Dúvida", author: "Carol M.", date: "2026-08-07", score: 8, body: "O código parece certo no editor, mas dá erro de identação. Só começou depois que colei um trecho vindo de outro arquivo.", comments: [{ author: "Marina S.", body: "Deve ter misturado tab com espaço — dá pra configurar o editor pra mostrar isso.", date: "2026-08-07" }, { author: "Carol M.", body: "Era exatamente isso, obrigada!", date: "2026-08-07" }] },
  { id: "p6", kind: "post", subjectCode: "INF1316", subjectName: "Sistemas Operacionais", title: "Aviso: monitoria extra antes da P2", tag: "Aviso", author: "João V.", date: "2026-08-06", score: 12, body: "A monitoria de Sistemas Operacionais vai abrir um horário extra na semana da P2, quinta às 18h.", comments: [] },
  { id: "p7", kind: "post", subjectCode: "FIS1053", subjectName: "Física 1", title: "Vale a pena fazer as listas extras de Física 1?", tag: "Discussão", author: "Bia N.", date: "2026-07-31", score: 5, body: "O professor passou umas listas que não valem nota. Pra quem já fez, ajudou bastante pra prova ou é melhor focar só nos exercícios do livro?", comments: [{ author: "João V.", body: "Ajudou bastante pra mim, principalmente as de dinâmica.", date: "2026-08-01" }] },
];
